import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(
    readFileSync(resolve(root, "package.json"), "utf8"),
);
const target = resolve(root, "src", "version.ts");
const source = [
    "// Generated by scripts/sync-version.mjs from package.json. Do not edit.",
    `export const version = ${JSON.stringify(packageJson.version)};`,
    "",
].join("\n");

if (!existsSync(target) || readFileSync(target, "utf8") !== source) {
    writeFileSync(target, source);
}
